# Generated by Django 4.2.7 on 2023-11-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_no', models.CharField(default=main.models.gen_app_no, max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True)),
                ('phone', models.CharField(max_length=13)),
                ('alt_phone', models.CharField(max_length=13)),
                ('address', models.TextField(blank=True)),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('ssc', models.CharField(max_length=100)),
                ('ssc_per', models.CharField(max_length=4)),
                ('hsc', models.CharField(max_length=100)),
                ('hsc_per', models.CharField(max_length=4)),
                ('grad', models.DateField(blank=True)),
                ('gujcet', models.CharField(max_length=10)),
                ('jee', models.CharField(max_length=10)),
                ('app_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1)),
                ('id_proof', models.FileField(default=None, max_length=250, upload_to='<django.db.models.fields.CharField>/')),
                ('photo', models.ImageField(default=None, max_length=250, upload_to='<django.db.models.fields.CharField>/')),
                ('marks_10', models.FileField(default=None, max_length=250, upload_to='<django.db.models.fields.CharField>/')),
                ('marks_12', models.FileField(default=None, max_length=250, upload_to='<django.db.models.fields.CharField>/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['app_status'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ques', models.TextField()),
                ('op1', models.TextField()),
                ('op2', models.TextField()),
                ('op3', models.TextField()),
                ('op4', models.TextField()),
                ('ans', models.TextField(choices=[('1', 'op1'), ('2', 'op2'), ('3', 'op3'), ('4', 'op4')])),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_flag', models.CharField(choices=[('E', 'Every-Site-Visitor'), ('Q', 'All-Applicants'), ('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('S', 'Specific-Applicant')], default='S', max_length=1)),
                ('content', models.CharField(max_length=100)),
                ('recipient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('1', 'op1'), ('2', 'op2'), ('3', 'op3'), ('4', 'op4')], max_length=1, null=True)),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.application')),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.question')),
            ],
            options={
                'unique_together': {('app_no', 'ques')},
            },
        ),
    ]
