# Generated by Django 4.2.7 on 2023-11-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_application_marks_10_application_marks_12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='marks_10',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='10marks/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='marks_12',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='12marks/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='photo/'),
        ),
    ]
