# Generated by Django 4.2.7 on 2023-11-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_application_marks_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='marks_10',
        ),
        migrations.RemoveField(
            model_name='application',
            name='marks_12',
        ),
    ]
