# Generated by Django 4.2.7 on 2023-11-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_application_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='photo',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='photo/'),
        ),
    ]
