# Generated by Django 4.2.7 on 2023-11-10 19:23

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_application_marks_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_no',
            field=models.CharField(default=main.models.gen_app_no, max_length=12),
        ),
    ]
