# Generated by Django 4.2.7 on 2023-11-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_application_marks_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='alt_phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='father',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer Not To Say')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='gujcet',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='hsc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='hsc_per',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='id_proof',
            field=models.FileField(default=None, max_length=250, upload_to='<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='application',
            name='jee',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mother',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='ssc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='ssc_per',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
