# Generated by Django 4.2.7 on 2023-11-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_test_test_end_alter_test_test_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='time_left',
        ),
    ]
