# Generated by Django 4.2.7 on 2023-11-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_test_time_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='test_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='test_start',
            field=models.DateTimeField(null=True),
        ),
    ]
