# Generated by Django 4.2.7 on 2023-11-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_application_test_end_application_test_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
