# Generated by Django 4.2.7 on 2023-11-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_application_order_id_application_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='test_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='test_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
