# Generated by Django 4.2.5 on 2023-11-26 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_application_test_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
