# Generated by Django 4.2.7 on 2023-11-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_application_marks_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='photo',
        ),
    ]
