# Generated by Django 4.2.7 on 2023-11-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_application_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='marks_10',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='10marks/'),
        ),
        migrations.AddField(
            model_name='application',
            name='marks_12',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='12marks/'),
        ),
    ]
