# Generated by Django 4.2.5 on 2023-11-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_notification_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='applicant_needed_for_specific_notification',
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application'),
        ),
    ]
