# Generated by Django 4.2.7 on 2023-11-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_notification_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='marks_10',
            field=models.FileField(default=None, max_length=250, upload_to='<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='application',
            name='marks_12',
            field=models.FileField(default=None, max_length=250, upload_to='<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(default=None, max_length=250, upload_to='<django.db.models.fields.CharField>'),
        ),
        migrations.CreateModel(
            name='ApplicantResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('1', 'op1'), ('2', 'op2'), ('3', 'op3'), ('4', 'op4')], max_length=1, null=True)),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.application')),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.question')),
            ],
            options={
                'unique_together': {('app_no', 'ques')},
            },
        ),
    ]
