# Generated by Django 4.2.7 on 2023-11-18 18:04

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_application_alt_phone_application_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id_proof',
            field=models.FileField(default=None, max_length=250, upload_to=main.models.file_upload),
        ),
        migrations.AlterField(
            model_name='application',
            name='marks_10',
            field=models.FileField(default=None, max_length=250, upload_to=main.models.file_upload),
        ),
        migrations.AlterField(
            model_name='application',
            name='marks_12',
            field=models.FileField(default=None, max_length=250, upload_to=main.models.file_upload),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(default=None, max_length=250, upload_to=main.models.file_upload),
        ),
    ]
