# Generated by Django 4.2.7 on 2023-11-19 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_applicantresponse_response_alter_question_qid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_start', models.DateTimeField()),
                ('test_end', models.DateTimeField()),
                ('time_left', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('score', models.IntegerField(default=0)),
                ('app_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.application')),
            ],
        ),
    ]
