# Generated by Django 4.2.5 on 2023-12-01 13:39

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_deadline_application_city_application_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to=main.models.file_upload),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='name',
            field=models.CharField(choices=[('app_start', 'Applicaton Start'), ('app_end', 'Application End'), ('test_start', 'Test Start'), ('test_end', 'Test End')], max_length=50),
        ),
    ]
